# Generated by Django 2.2 on 2022-06-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_auto_20220607_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(max_length=250),
        ),
    ]
