# Generated by Django 2.2 on 2022-06-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_auto_20220607_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='avilable',
            field=models.BooleanField(default=True),
        ),
    ]
